SELECT
  far_det_pac_car.far_detpaccar_pk,
  far_det_pac_car.far_prep_det_pk,
  far_det_pac_car.cod_art_mc_pk,
  far_det_pac_car.far_detpaccar_uni,
  far_det_pac_car.far_detpaccar_cad,
  far_det_pac_car.far_detpaccar_ok,
  far_det_pac_car.linea_orden_pk,
  far_det_pac_car.mov_alma_linpk,
  far_det_pac_car.far_detpaccar_txt,
  far_det_pac_car.far_detmed_dosis,
  far_det_pac_car.far_detmed_dia,
  far_det_pac_car.far_detmed_hora,
  far_det_pac_car.far_detmed_tipo,
  far_det_pac_car.far_detmed_int,
  far_det_pac_car.far_detmed_cn,
  far_det_pac_car.far_detmed_den,
  far_det_pac_car.codigo_cliente,
  far_det_pac_car.cod_cama,
  far_det_pac_car.far_prep_car_pk,
  far_det_pac_car.cod_habitacion,
  far_det_pac_car.far_detpaccar_cant,
  far_det_pac_car.far_detpaccar_iva,
  far_det_pac_car.far_detmod,
  far_det_pac_car.almacen_pk,
  far_det_pac_car.far_destino_pk,
  far_det_pac_car.protocab_pk,
  far_det_pac_car.episodio_act,
  far_det_pac_car.medico_pk,
  0 as c_lote,
  0 as c_estupef,
  far_det_pac_car.far_detpaccar_pre,
  0 as self,
  far_det_pac_car.usuario_pk,
  far_det_pac_car.fdpc_facturado,
  far_det_pac_car.fdpc_fechasys,
  far_det_pac_car.lotecab_pk,
  alm_lote_cab.lotecab_num,
  alm_lote_cab.lotecab_f_cad,
  far_det_pac_car.ana_unid_pk,
  far_det_pac_car.formasfar_pk,
  far_det_pac_car.fdpc_tipo_dosis,
  far_det_pac_car.fdpc_precio_medio,
  far_det_pac_car.fdpc_ingta_pk,
  far_det_pac_car.uc_pk,
  far_det_pac_car.fdpc_usu_confirm,
  far_det_pac_car.fdpc_dia_confirm,
  far_det_pac_car.fdpc_hora_confirm,
  far_det_pac_car.fdpc_origen,
  far_det_pac_car.fdpc_estado_hp,
  1 as cc_far_mat,
  alm_articulos_mc.art_relcon_med,
  alm_articulos_mc.ana_unid_pk,
  alm_articulos_mc.mc_fac_conver,
  far_det_pac_car.fdpc_num_protoc,
  alm_articulos_mc.catp_carart_pk,
  alm_articulos_mc.catp_tipopro_pk,
  alm_articulos_mc.art_estupef,
  0.001 as cc_cant_max,
  far_det_pac_car.fdpc_fecha_adm,
  far_det_pac_car.fdpc_hora_adm,
  0 as cc_diluyente,
  far_det_pac_car.fdpc_dosis_conf,
  far_det_pac_car.fdpc_cant_conf,
  far_det_pac_car.vias_pk,
  far_det_pac_car.fdpc_modo_disp,
  alm_articulos_mc.art_implante,
  alm_almacenes.tipo_alma_pk,
  far_det_pac_car.fdpc_pend_carga,
  far_det_pac_car.fdpc_usu_regula,
  far_det_pac_car.fdpc_fecha_regula,
  far_det_pac_car.fdpc_hora_regula,
  0 as cc_pdte_firma_otro,
  0 as cc_pdte_firma_enf,
  alm_articulos_mc.art_multidosis,
  0 as cc_fdpc_asoc
FROM
  far_det_pac_car
  LEFT OUTER JOIN alm_lote_cab ON far_det_pac_car.lotecab_pk = alm_lote_cab.lotecab_pk
  LEFT OUTER JOIN alm_almacenes ON far_det_pac_car.almacen_pk = alm_almacenes.almacen_pk
  LEFT OUTER JOIN alm_articulos_mc ON far_det_pac_car.cod_art_mc_pk = alm_articulos_mc.cod_art_mc_pk
WHERE
  (far_det_pac_car.codigo_cliente = 100215702)
  and (far_det_pac_car.fdpc_facturado = 1)
  and (far_det_pac_car.fdpc_estado_hp in (4, 11) or far_det_pac_car.fdpc_estado_hp is null)